In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("diamonds.csv")

In [3]:
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [4]:
df.tail()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  53940 non-null  int64
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  object
 3   color       53940 non-null  object
 4   clarity     53940 non-null  object
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.5+ MB

In [6]:
df.isnull().sum()

Unnamed: 0    0
carat         0
cut           0
color         0
clarity       0
depth         0
table         0
price         0
x             0
y             0
z             0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.shape

(53940, 11)

In [9]:
df.nunique()

Unnamed: 0    53940
carat           273
cut               5
color             7
clarity           8
depth           184
table           127
price         11602
x               554
y               552
z               375
dtype: int64

In [10]:
y=df["price"]

In [11]:
x=df.drop(["price"],axis=1)

In [12]:
x.shape

(53940, 10)

In [13]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  53940 non-null  int64
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  object
 3   color       53940 non-null  object
 4   clarity     53940 non-null  object
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   x           53940 non-null  float64
 8   y           53940 non-null  float64
 9   z           53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,StandardScaler
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[2,3,4]),
                                   ("sc",StandardScaler(),[0,1,5,6,7,8,9])])

In [15]:
x_transform=ct.fit_transform(x)

In [16]:
x_transform=pd.DataFrame(x_transform,columns=x.columns)
x_transform

,Unnamed: 0,carat,cut,color,clarity,depth,table,x,y,z
0,2.0,1.0,3.0,-1.732019,-1.198168,-0.174092,-1.099672,-1.587837,-1.536196,-1.571129
1,3.0,1.0,2.0,-1.731954,-1.240361,-1.360738,1.585529,-1.641325,-1.658774,-1.741175
2,1.0,1.0,4.0,-1.731890,-1.198168,-3.385019,3.375663,-1.498691,-1.457395,-1.741175
3,3.0,5.0,5.0,-1.731826,-1.071587,0.454133,0.242928,-1.364971,-1.317305,-1.287720
4,1.0,6.0,3.0,-1.731762,-1.029394,1.082358,0.242928,-1.240167,-1.212238,-1.117674
...,...,...,...,...,...,...,...,...,...,...
53935,2.0,0.0,2.0,1.731762,-0.164427,-0.662711,-0.204605,0.016798,0.022304,-0.054888
53936,1.0,0.0,2.0,1.731826,-0.164427,0.942753,-1.099672,-0.036690,0.013548,0.100988
53937,4.0,0.0,2.0,1.731890,-0.206621,0.733344,1.137995,-0.063434,-0.047741,0.030135
53938,3.0,4.0,3.0,1.731954,0.130927,-0.523105,0.242928,0.373383,0.337506,0.285204
53939,2.0,0.0,3.0,1.732019,-0.101137,0.314528,-1.099672,0.088115,0.118616,0.143499

In [ ]:
from sklearn.feature_selection import mutual_info_classif
mf=mutual_info_classif(x_transformed,y)