In [1]:
import numpy as np
import pandas as pd

In [2]:
# load dataset
df=pd.read_csv("banana_quality_dataset.csv")
df.head()

,sample_id,variety,region,quality_score,quality_category,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,harvest_date,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
0,1,Manzano,Colombia,1.88,Processing,2.11,Turning,16.83,3.53,21.44,146.92,2023-10-16,13.7,58.2,2440.5,183.6
1,2,Plantain,Guatemala,2.42,Processing,4.25,Ripe,16.73,4.09,26.11,160.48,2023-10-14,5.1,280.2,2374.6,109.8
2,3,Burro,Ecuador,3.57,Premium,6.24,Overripe,21.34,1.63,25.20,225.27,2023-09-08,17.7,1246.9,1191.5,147.7
3,4,Manzano,Ecuador,2.21,Processing,5.39,Ripe,16.75,3.31,13.08,137.80,2023-10-07,13.0,1150.2,2845.1,92.8
4,5,Red Dacca,Ecuador,2.35,Processing,5.84,Ripe,16.90,3.07,12.98,227.84,2023-10-02,4.8,526.0,2136.9,129.7

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sample_id           1000 non-null   int64
 1   variety             1000 non-null   object
 2   region              1000 non-null   object
 3   quality_score       1000 non-null   float64
 4   quality_category    1000 non-null   object
 5   ripeness_index      1000 non-null   float64
 6   ripeness_category   1000 non-null   object
 7   sugar_content_brix  1000 non-null   float64
 8   firmness_kgf        1000 non-null   float64
 9   length_cm           1000 non-null   float64
 10  weight_g            1000 non-null   float64
 11  harvest_date        1000 non-null   object
 12  tree_age_years      1000 non-null   float64
 13  altitude_m          1000 non-null   float64
 14  rainfall_mm         1000 non-null   float64
 15  soil_nitrogen_ppm   1000 non-null   float64
dtypes: float64(10), int64(1), object(5)
memory usage: 125.1+ KB

In [4]:
df.tail()

,sample_id,variety,region,quality_score,quality_category,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,harvest_date,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
995,996,Burro,Ecuador,3.50,Good,4.94,Ripe,21.06,2.49,27.95,196.35,2023-10-04,12.4,409.7,2029.9,173.0
996,997,Cavendish,Philippines,2.38,Processing,6.74,Overripe,16.10,2.00,12.39,165.55,2023-09-23,14.0,314.3,1330.7,180.5
997,998,Plantain,Ecuador,1.68,Processing,1.41,Green,17.17,2.28,16.56,210.08,2023-10-19,18.4,683.0,2955.4,189.9
998,999,Fehi,Guatemala,2.02,Processing,1.34,Green,17.03,2.88,26.31,162.50,2023-09-22,8.2,1362.7,1215.8,85.5
999,1000,Red Dacca,Ecuador,2.69,Good,2.69,Turning,21.10,1.23,21.95,105.39,2023-09-29,13.2,156.7,2863.9,51.3

In [5]:
df.isnull().sum()

sample_id             0
variety               0
region                0
quality_score         0
quality_category      0
ripeness_index        0
ripeness_category     0
sugar_content_brix    0
firmness_kgf          0
length_cm             0
weight_g              0
harvest_date          0
tree_age_years        0
altitude_m            0
rainfall_mm           0
soil_nitrogen_ppm     0
dtype: int64

In [6]:
df.drop(["sample_id","harvest_date"],axis=1,inplace=True)

In [7]:
y=df["quality_score"]

In [8]:
## input varibles 13 columns
x=df.drop(["quality_score"],axis=1)

In [9]:
x.shape

(1000, 13)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,StandardScaler
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,1,2,4]),
                                   ("sc",StandardScaler(),[3,5,6,7,8,9,10,11,12])])

In [11]:
x_transform=ct.fit_transform(x)
x_transform=pd.DataFrame(x_transform,columns=x.columns)
x_transform

,variety,region,quality_category,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
0,5.0,1.0,2.0,3.0,-1.102626,-0.829400,0.638798,0.271721,-0.362627,0.541038,-1.557632,0.828641,1.478299
1,6.0,4.0,2.0,2.0,0.118602,-0.878570,1.073376,1.086240,-0.086672,-1.108701,-1.037919,0.711835,0.100944
2,1.0,3.0,1.0,1.0,1.254230,1.388129,-0.835662,0.927522,1.231846,1.308358,1.225172,-1.385170,0.808285
3,5.0,3.0,2.0,2.0,0.769163,-0.868736,0.468071,-1.186389,-0.548225,0.406757,0.998792,1.545781,-0.216332
4,7.0,3.0,2.0,2.0,1.025963,-0.794982,0.281824,-1.203830,1.284148,-1.166250,-0.462490,0.290520,0.472345
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1.0,3.0,0.0,2.0,0.512362,1.250456,-0.168275,1.407163,0.643306,0.291659,-0.734754,0.100866,1.280467
996,2.0,7.0,2.0,1.0,1.539564,-1.188335,-0.548530,-1.306735,0.016506,0.598587,-0.958090,-1.138442,1.420442
997,6.0,3.0,2.0,0.0,-1.502094,-0.662225,-0.331241,-0.579424,0.922720,1.442639,-0.094945,1.741284,1.595878
998,3.0,4.0,2.0,0.0,-1.542040,-0.731062,0.134378,1.121123,-0.045564,-0.514028,1.496265,-1.342099,-0.352575
999,7.0,3.0,0.0,3.0,-0.771639,1.270123,-1.146075,0.360673,-1.207789,0.445123,-1.327039,1.579103,-0.990861

In [12]:
from sklearn.feature_selection import mutual_info_regression
mf=mutual_info_regression(x_transform,y)
mf=pd.Series(mf)
mf.index=x_transform.columns
mf.sort_values(ascending=False)

quality_category      0.915047
ripeness_category     0.322413
sugar_content_brix    0.274265
ripeness_index        0.264101
length_cm             0.137691
firmness_kgf          0.038296
rainfall_mm           0.031864
weight_g              0.031621
altitude_m            0.021110
soil_nitrogen_ppm     0.018069
region                0.017503
variety               0.009288
tree_age_years        0.000000
dtype: float64

In [13]:
x.drop(["tree_age_years","region","soil_nitrogen_ppm","variety" ,"altitude_m"],axis=1,inplace=True)

In [14]:
x.shape

(1000, 8)

In [15]:
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,2]),
                                   ("sc",StandardScaler(),[1,3,4,5,6,7])])

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [17]:
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,2]),
                                   ("sc",StandardScaler(),[1,3,4,5,6,7])])

In [18]:
x_train_transform=ct.fit_transform(x_train)
x_tarin_transorm=pd.DataFrame(x_train_transform)

In [19]:
x_test_transform=ct.transform(x_test)
x_test_transform=pd.DataFrame(x_test_transform)

In [20]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(kn, x_train_transform, y_train, cv=5)
score

NameError: name 'kn' is not defined

In [22]:
from sklearn.neighbors import KNeighborsRegressor
kn= KNeighborsRegressor(n_neighbors=5)
kn.fit(x_train_transform,y_train)

KNeighborsRegressor()

In [21]:
#predict
y_pred=kn.predict(x_test_transform)

NameError: name 'kn' is not defined

In [26]:
# evolution
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

NameError: name 'y_pred' is not defined

In [24]:
y_train_pred=kn.predict(x_train_transform)

In [25]:
r=r2_score(y_train,y_train_pred)
r

0.9476531846490244

## HyperParameter Tuning

In [27]:
import warnings
warnings.filterwarnings("ignore")

In [30]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor

kn = KNeighborsRegressor()

param_grid = {
    'n_neighbors': [3,5,7,9],    # list(range(5,50))
    'weights': ['uniform', 'distance'],
    'p': [1,2]
}
grid = GridSearchCV(estimator=kn, param_grid=param_grid, cv=5, scoring='r2', verbose=1)
grid.fit(x_train_transform,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': [3, 5, 7, 9], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='r2', verbose=1)

In [31]:
print(grid.best_params_)
print(grid.best_score_)

{'n_neighbors': 5, 'p': 2, 'weights': 'distance'}
0.9203702879097284