In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# load dataset
df=pd.read_csv("loan_approved.csv")
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Loan_ID                 614 non-null    object
 1   Gender                  601 non-null    object
 2   Married                 611 non-null    object
 3   Dependents              599 non-null    object
 4   Education               614 non-null    object
 5   Self_Employed           582 non-null    object
 6   ApplicantIncome         614 non-null    int64
 7   CoapplicantIncome       614 non-null    float64
 8   LoanAmount              592 non-null    float64
 9   Loan_Amount_Term        600 non-null    float64
 10  Credit_History          564 non-null    float64
 11  Property_Area           614 non-null    object
 12  Loan_Status (Approved)  614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [4]:
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [5]:
df.isnull().sum()

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [6]:
num_cols = df.select_dtypes(include='number').columns
cat_cols = df.select_dtypes(include='object').columns

print("Numerical columns:", num_cols)
print("Categorical columns:", cat_cols)

Numerical columns: Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History'],
      dtype='object')
Categorical columns: Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'Property_Area', 'Loan_Status (Approved)'],
      dtype='object')

In [7]:
for col in num_cols:
    df[col].fillna(df[col].mean(), inplace=True)

In [8]:
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Loan_ID                 614 non-null    object
 1   Gender                  614 non-null    object
 2   Married                 614 non-null    object
 3   Dependents              614 non-null    object
 4   Education               614 non-null    object
 5   Self_Employed           614 non-null    object
 6   ApplicantIncome         614 non-null    int64
 7   CoapplicantIncome       614 non-null    float64
 8   LoanAmount              614 non-null    float64
 9   Loan_Amount_Term        614 non-null    float64
 10  Credit_History          614 non-null    float64
 11  Property_Area           614 non-null    object
 12  Loan_Status (Approved)  614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [10]:
y=df["Loan_Status (Approved)"]

In [11]:
## input varibles 13 columns
x=df.drop(["Loan_Status (Approved)"],axis=1)

In [17]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         614 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,StandardScaler
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,1,2,3,4,5,11]),
                                   ("sc",StandardScaler(),[6,7,8,9,10])])

In [19]:
x_transformed=ct.fit_transform(x)

In [20]:
x_transformed

array([[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  2.79850543e-01,  4.51640451e-01],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
        -2.19273315e-01,  2.79850543e-01,  4.51640451e-01],
       [ 2.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
        -9.57640999e-01,  2.79850543e-01,  4.51640451e-01],
       ...,
       [ 6.11000000e+02,  1.00000000e+00,  1.00000000e+00, ...,
         1.26937121e+00,  2.79850543e-01,  4.51640451e-01],
       [ 6.12000000e+02,  1.00000000e+00,  1.00000000e+00, ...,
         4.83366900e-01,  2.79850543e-01,  4.51640451e-01],
       [ 6.13000000e+02,  0.00000000e+00,  0.00000000e+00, ...,
        -1.59727534e-01,  2.79850543e-01, -2.41044061e+00]],
      shape=(614, 12))

In [23]:
x_transformed=pd.DataFrame(x_transformed,columns=x.columns)
x_transformed

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.072991,-0.554487,0.000000,0.279851,0.451640
1,1.0,1.0,1.0,1.0,0.0,0.0,0.0,-0.134412,-0.038732,-0.219273,0.279851,0.451640
2,2.0,1.0,1.0,0.0,0.0,1.0,2.0,-0.393747,-0.554487,-0.957641,0.279851,0.451640
3,3.0,1.0,1.0,0.0,1.0,0.0,2.0,-0.462062,0.251980,-0.314547,0.279851,0.451640
4,4.0,1.0,0.0,0.0,0.0,0.0,2.0,0.097728,-0.554487,-0.064454,0.279851,0.451640
...,...,...,...,...,...,...,...,...,...,...,...,...
609,609.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.410130,-0.554487,-0.898095,0.279851,0.451640
610,610.0,1.0,1.0,3.0,0.0,0.0,0.0,-0.212557,-0.554487,-1.267279,-2.518655,0.451640
611,611.0,1.0,1.0,1.0,0.0,0.0,2.0,0.437174,-0.472404,1.269371,0.279851,0.451640
612,612.0,1.0,1.0,2.0,0.0,0.0,2.0,0.357064,-0.554487,0.483367,0.279851,0.451640
613,613.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.134412,-0.554487,-0.159728,0.279851,-2.410441

In [27]:
from sklearn.feature_selection import mutual_info_classif
mf=mutual_info_classif(x_transformed,y)
mf=pd.Series(mf)
mf.index=x_transformed.columns
mf.sort_values(ascending=False)

Property_Area        0.126352
ApplicantIncome      0.055275
LoanAmount           0.023107
Gender               0.022826
Education            0.019707
Credit_History       0.015453
CoapplicantIncome    0.008243
Loan_ID              0.000000
Married              0.000000
Dependents           0.000000
Self_Employed        0.000000
Loan_Amount_Term     0.000000
dtype: float64

In [29]:
x.drop(["Loan_Amount_Term","Self_Employed","Dependents","Married","Loan_ID","CoapplicantIncome"], axis=1,inplace=True)

In [31]:
x.shape

(614, 6)

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [40]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           614 non-null    object
 1   Education        614 non-null    object
 2   ApplicantIncome  614 non-null    int64
 3   LoanAmount       614 non-null    float64
 4   Credit_History   614 non-null    float64
 5   Property_Area    614 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 28.9+ KB

In [41]:
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,1,5]),
                                   ( "sc",StandardScaler(),[2,3,4])])

In [44]:
x_train_transform=ct.fit_transform(x_train)
x_train_transform=pd.DataFrame(x_train_transform)
x_train_transform

       0    1    2         3         4         5
0    1.0  0.0  1.0 -0.391178 -0.625678  0.454349
1    1.0  1.0  1.0 -0.363725 -0.292819 -2.394324
2    1.0  0.0  2.0  0.762314  0.468001 -2.394324
3    1.0  0.0  0.0  0.594681  2.762349  0.454349
4    1.0  0.0  1.0  0.327051  0.325347  0.454349
..   ...  ...  ...       ...       ...       ...
486  1.0  0.0  0.0 -0.363571 -0.102614  0.454349
487  1.0  0.0  1.0 -0.263574 -0.197716  0.454349
488  1.0  1.0  0.0 -0.439029 -0.518687  0.454349
489  1.0  0.0  2.0 -0.106677 -0.209604  0.454349
490  1.0  0.0  1.0 -0.039962  0.087591  0.454349

[491 rows x 6 columns]

In [46]:
x_test_transform=ct.fit_transform(x_test)
x_test_transform=pd.DataFrame(x_test_transform)

In [47]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier( n_neighbors=5,metric='minkowski',p=2)

In [48]:
kn.fit(x_train_transform,y_train)

KNeighborsClassifier()

In [50]:
y_pred=kn.predict(x_test_transform)

In [51]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
ac=accuracy_score(y_test,y_pred)
ac

0.8130081300813008

In [52]:
pr=precision_score(y_test,y_pred,average="micro")
pr

0.8130081300813008

In [53]:
f1=f1_score(y_test,y_pred,average="micro")
f1

0.8130081300813008