In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [4]:
df=pd.read_csv("output.csv")
df.head(10)

                                              Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1
5     Now I am getting angry and I want my damn pho.      0
6              Honeslty it didn't taste THAT fresh.)      0
7  The potatoes were like rubber and you could te...      0
8                          The fries were great too.      1
9                                     A great touch.      1

In [7]:
df.value_counts().sum()

np.int64(1000)

In [8]:
df.isnull().sum()

 Review    0
Liked      0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0    Review  1000 non-null   object
 1   Liked    1000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

In [14]:
df["review_length"] = df[" Review"].apply(lambda x: len(str(x).split()))
df["review_length"]

0       4
1       4
2       8
3      15
4      12
       ..
995    12
996     3
997    10
998    16
999    28
Name: review_length, Length: 1000, dtype: int64

# TASK 2: Clean & Preprocess the Text

In [17]:
df["review"] = df[" Review"].str.lower()

In [19]:
import re

# Remove punctuation from dataframe column
df["review"] = df[" Review"].apply(
    lambda x: re.sub(r'[^\w\s]', '', str(x))
)

In [20]:
df["review"] = df[" Review"].apply(
    lambda x: re.sub(r'\d+', '', str(x))
)

In [22]:
df["review"] = df[" Review"].apply(
    lambda x: re.sub(r'\s+', ' ', str(x)).strip()
)

In [23]:
df["review"]

0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I hadn't wasted enough of my life ...
Name: review, Length: 1000, dtype: object

## Remove stopwords

In [26]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vinod\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\vinod\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [27]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words=set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vinod\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [29]:
df["review"] = df[" Review"].apply(
    lambda x: ' '.join(
        word for word in str(x).split()
        if word.lower() not in stop_words
    )
)

In [30]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

df["review"] = df[" Review"].apply(
    lambda x: ' '.join(
        stemmer.stem(word) for word in str(x).split()
    )
)

In [31]:
import re

def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags
        "]+",
        flags=re.UNICODE
    )
    
    return emoji_pattern.sub(r'', str(text))

df["review"] = df[" Review"].apply(remove_emojis)

# TASK 3: Convert Text to Numerical Features

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

x = cv.fit_transform(df[" Review"])

In [33]:
bow_df = pd.DataFrame(
    x.toarray(),
    columns=cv.get_feature_names_out()
)

bow_df

,00,10,100,11,12,15,17,1979,20,2007,...,yelpers,yet,you,your,yourself,yucky,yukon,yum,yummy,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# TASK 4: Split the Data

In [36]:
from sklearn.model_selection import train_test_split

# Features and target
X = df[" Review"]
y = df["Liked"]

# Split data
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2)


print(x_train.shape)
print(x_test.shape)

(800,)
(200,)

# TASK 5: Train Naïve Bayes Models

In [38]:
x_train_bow = cv.fit_transform(x_train)
x_test_bow = cv.transform(x_test)

# Train Bernoulli Naive Bayes model
bnb = BernoulliNB()

bnb.fit(x_train_bow, y_train)

BernoulliNB()

In [40]:
y_pred = bnb.predict(x_test_bow)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0])

In [42]:
from sklearn.metrics import accuracy_score, classification_report
print("Accuracy:", accuracy_score(y_test, y_pred))

# Classification report
print(classification_report(y_test, y_pred))

Accuracy: 0.8
              precision    recall  f1-score   support

           0       0.87      0.74      0.80       108
           1       0.74      0.87      0.80        92

    accuracy                           0.80       200
   macro avg       0.81      0.81      0.80       200
weighted avg       0.81      0.80      0.80       200

In [44]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Model
bnb = BernoulliNB()

# Train
bnb.fit(x_train_bow, y_train)

# Predict
y_pred_bnb = bnb.predict(x_test_bow)

# Metrics
print("Accuracy :", accuracy_score(y_test, y_pred_bnb))
print("Precision:", precision_score(y_test, y_pred_bnb))
print("Recall   :", recall_score(y_test, y_pred_bnb))
print("F1 Score :", f1_score(y_test, y_pred_bnb))

# Confusion Matrix
print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_bnb))
# Classification Report
print("\nClassification Report")
print(classification_report(y_test, y_pred_bnb))

Accuracy : 0.8
Precision: 0.7407407407407407
Recall   : 0.8695652173913043
F1 Score : 0.8

Confusion Matrix
[[80 28]
 [12 80]]

Classification Report
              precision    recall  f1-score   support

           0       0.87      0.74      0.80       108
           1       0.74      0.87      0.80        92

    accuracy                           0.80       200
   macro avg       0.81      0.81      0.80       200
weighted avg       0.81      0.80      0.80       200

## TASK 7: Predict Sentiment of New Reviews

In [46]:
sample_reviews = [
    "The food was fantastic!",
    "Worst service ever."
]

# Convert text into vectors
sample_vectors = cv.transform(sample_reviews)

# Predict sentiment
predictions = bnb.predict(sample_vectors)

# Show results
for review, pred in zip(sample_reviews, predictions):
    print("Review :", review)
    print("Prediction :", pred)
    print("-" * 40)

Review : The food was fantastic!
Prediction : 1
----------------------------------------
Review : Worst service ever.
Prediction : 0
----------------------------------------

In [47]:
pip install streamlit

Requirement already satisfied: streamlit in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (1.51.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging<26,>=20 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)
Requirement already satisfied: attrs>=22.2.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vinod\onedrive\documents\anaconda3_2\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [52]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# Load dataset
df = pd.read_csv("output.csv")

# Features and target
X = df[" Review"]
y = df["Liked"]

# Split
x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Vectorization
cv = CountVectorizer()

x_train_bow = cv.fit_transform(x_train)

# Train model
model = MultinomialNB()

model.fit(x_train_bow, y_train)

# Save model
joblib.dump(model, "sentiment_model.pkl")

# Save vectorizer
joblib.dump(cv, "vectorizer.pkl")

print("Files saved successfully")

Files saved successfully