In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("social_media.csv")

df.head(5)

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   age                             30000 non-null  int64
 1   gender                          30000 non-null  object
 2   job_type                        30000 non-null  object
 3   daily_social_media_time         27235 non-null  float64
 4   social_platform_preference      30000 non-null  object
 5   number_of_notifications         30000 non-null  int64
 6   work_hours_per_day              30000 non-null  float64
 7   perceived_productivity_score    28386 non-null  float64
 8   actual_productivity_score       27635 non-null  float64
 9   stress_level                    28096 non-null  float64
 10  sleep_hours                     27402 non-null  float64
 11  screen_time_before_sleep        27789 non-null  float64
 12  breaks_during_work              30000 non-null  int64
 13  uses_focus_apps                 30000 non-null  bool
 14  has_digital_wellbeing_enabled   30000 non-null  bool
 15  coffee_consumption_per_day      30000 non-null  int64
 16  days_feeling_burnout_per_month  30000 non-null  int64
 17  weekly_offline_hours            30000 non-null  float64
 18  job_satisfaction_score          27270 non-null  float64
dtypes: bool(2), float64(9), int64(5), object(3)
memory usage: 3.9+ MB

## Task 2

In [5]:
X = df.drop('job_satisfaction_score', axis=1)

## Task 3: Identify Feature Types

In [7]:
num_col=df.select_dtypes(include="number").columns
print(num_col)

Index(['age', 'daily_social_media_time', 'number_of_notifications',
       'work_hours_per_day', 'perceived_productivity_score',
       'actual_productivity_score', 'stress_level', 'sleep_hours',
       'screen_time_before_sleep', 'breaks_during_work',
       'coffee_consumption_per_day', 'days_feeling_burnout_per_month',
       'weekly_offline_hours', 'job_satisfaction_score'],
      dtype='object')

In [8]:
cat_col=df.select_dtypes(include="object").columns
print(cat_col)

Index(['gender', 'job_type', 'social_platform_preference'], dtype='object')

In [10]:
categorical_cols = X.select_dtypes(include=['object', 'category']).columns
print(categorical_cols)

Index(['gender', 'job_type', 'social_platform_preference'], dtype='object')

In [11]:
binary_cols = []
nominal_cols = []

for col in categorical_cols:
    unique_vals = X[col].nunique()
    
    if unique_vals == 2:
        binary_cols.append(col)
    else:
        nominal_cols.append(col)

print("Binary categorical:", binary_cols)
print("Nominal categorical:", nominal_cols)

Binary categorical: []
Nominal categorical: ['gender', 'job_type', 'social_platform_preference']

## Task 4: Encode Categorical Variables

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

binary_cols = ['gender', 'uses_focus_apps', 'has_digital_wellbeing_enabled']

for col in binary_cols:
    X[col] = le.fit_transform(X[col])

In [16]:
X = pd.get_dummies(
    X,
    columns=['job_type', 'social_platform_preference'],
    drop_first=True
)

In [18]:
#from sklearn.preprocessing import StandardScaler

#scaler = StandardScaler()

##X[num_col] = scaler.fit_transform(X[num_col])

KeyError: "['job_satisfaction_score'] not in index"

## Task 6: Combine All Preprocessing Steps

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [20]:
pre=ColumnTransformer(transformers=[('ohe',OneHotEncoder(),cat_col),('sc',StandardScaler(),num_col)])

In [21]:
prep=pre.fit_transform(df)
prep

array([[ 0.        ,  1.        ,  0.        , ..., -0.49250667,
         1.58872949,  0.64671729],
       [ 0.        ,  1.        ,  0.        , ...,  1.02054852,
        -1.42310937, -0.73190023],
       [ 0.        ,  1.        ,  0.        , ...,  0.15594556,
        -0.00530341, -1.17386876],
       ...,
       [ 0.        ,  1.        ,  0.        , ..., -1.46518501,
        -1.16373598,  0.62246125],
       [ 1.        ,  0.        ,  0.        , ..., -0.70865741,
         0.29548475,  1.36237611],
       [ 0.        ,  1.        ,  0.        , ..., -1.24903427,
        -0.55433216,  1.14272147]], shape=(30000, 28))

## Task 7: Create Final Feature DataFrame

In [22]:
dfff=pd.DataFrame(prep)
dfff

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.250337,1.242338,-0.528229,-0.945166,-0.928250,0.947731,1.418913,-0.492507,1.588729,0.646717
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,-0.220971,0.113250,0.518419,-0.953806,-0.541903,0.632640,0.000496,1.020549,-1.423109,-0.731900
2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.814815,-0.784643,-0.528229,1.422819,-0.614058,-1.572998,0.709705,0.155946,-0.005303,-1.173869
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.282056,-1.686859,0.169536,-0.305512,0.273933,-1.257907,-1.417920,-1.249034,1.856513,-1.523336
4,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.659685,NaN,0.518419,-0.747649,1.302050,-1.257907,-0.708712,1.560925,0.040227,2.229050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,-1.068468,-0.789017,0.867302,-0.696586,0.592471,1.262822,1.418913,-1.140959,1.568106,NaN
29996,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.296174,0.906626,0.867302,-2.359910,-1.341763,-0.627725,-0.708712,1.452850,-0.858384,0.561351
29997,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.532304,1.968364,-0.179346,-0.689032,0.304171,1.577914,-0.708712,-1.465185,-1.163736,0.622461
29998,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.115226,1.032089,0.867302,0.215728,-1.210827,-1.257907,0.000496,-0.708657,0.295485,1.362376
29999,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.395733,0.239426,-0.877112,0.181014,-0.049711,0.002458,-0.708712,-1.249034,-0.554332,1.142721

In [23]:
X_df = X.copy()

In [24]:
X_df = pd.DataFrame(X, columns=X.columns)

## Task 8: Save Processed Data

In [25]:
X_df.to_csv('X_processed_data.csv', index=False)

In [26]:
print('job_satisfaction_score' in X_df.columns)

False